### PR TITLE
Update configure-hmr.md

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
@bniedermeyer Please merge this fix into your branch (and thus PR)

**Comment by bniedermeyer** [comment]
Sorry @robertbaker I didn't see this for some reason.

**Comment by bniedermeyer** [comment]
@robertbaker looks like there's been some big changes to docs in the last hour - looks like the docs directory has been removed?? I'm gonna let the dust settle before moving forward to see what's going on.

**Comment by bniedermeyer** [comment]
@robertbaker Can you please sign the CLA so this can be merged in once the docs have been fixed and I rebase? Thanks!

**Pull request merged**
